# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: "SandhataVmssPool"

variables:
  bkstrgrg: "sandhata"
  bkstrgacc: "sandhata"
  bkcontainer: "tfstate-sandhatafunc"
  bkstrgkey: "sandhatafunc.tfstate"

stages:
  - stage: TerraformBuild
    jobs:
      - job: Terraform
        continueOnError: false
        steps:
          - bash: |
              sudo apt-get install -y zip
            displayName: "Installing Zip"
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
            displayName: Install Terraform
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Sandhata (6f6b6f42-7704-42fa-b07a-9db961090f1b)-1646'
              backendAzureRmResourceGroupName: '$(bkstrgrg)'
              backendAzureRmStorageAccountName: '$(bkstrgacc)'
              backendAzureRmContainerName: '$(bkcontainer)'
              backendAzureRmKey: '$(bkstrgkey)'
            displayName: Terraform Init
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'validate'
            displayName: Terraform Validate
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'custom'
              customCommand: 'fmt'
              outputTo: 'console'
              environmentServiceNameAzureRM: 'Sandhata (6f6b6f42-7704-42fa-b07a-9db961090f1b)-1879'
            displayName: Terraform Fmt
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'custom'
              customCommand: '-chdir=$(Build.SourcesDirectory)'
              commandOptions: 'plan -out tfplanfile'
              outputTo: 'console'
              environmentServiceNameAzureRM: 'Sandhata (6f6b6f42-7704-42fa-b07a-9db961090f1b)-1879'
            displayName: Terraform Plan
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true
            displayName: Archive Files
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(Build.BuildId)-build'
              publishLocation: 'Container'
            displayName: Publishing Aritifact
          